services:

  nginx:
    image: nginx:stable-alpine
    ports:
      - "8000:80"
    volumes:
      - ./_docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./:/var/www/html/
    depends_on:
      - php
      - database
    networks:
      - backend


  php:
    build:
      context: '_docker/dockerfiles'
      dockerfile: php.Dockerfile
    volumes:
      - ./:/var/www/html
    networks:
      - backend


  database:
    image: mysql:latest
    container_name: database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: github_users
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3316:3306"
    volumes:
      - database_data:/var/lib/mysql
    networks:
      - backend


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8001:80"
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
    networks:
      - backend


  composer:
    build:
      context: _docker/dockerfiles
      dockerfile: composer.Dockerfile
    volumes:
      - ./:/var/www/html
    networks:
      - backend


  redis_server:
    image: redis:alpine
    container_name: redis_server
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - backend

  yii_console:
    build:
      context: '_docker/dockerfiles'
      dockerfile: php.Dockerfile
    volumes:
      - ./:/var/www/html
    networks:
      - backend

volumes:
  database_data:
  redis_data:

networks:
  backend:
    driver: bridge